### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by LUCANTON** [pupil-labs/pupil-detectors#20]
I have problems during installation of pupil-detectors...
I'm currently using Windows 10 with python version 3.8.5
I have the following error that I think is related tu Numpy version.. ( the version istalled is numpy==1.19.3)

```
C:\Users\anton\Desktop\pupil-detectors-master>pip install pupil-detectors
Collecting pupil-detectors
  Downloading pupil-detectors-2.0.1.tar.gz (238 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 238 kB 364 kB/s
  Installing build dependencies ... done
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\anton\appdata\local\programs\python\python38\python.exe' 'c:\users\anton\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\anton\AppData\Local\Temp\tmpvnrrlwvo'
       cwd: C:\Users\anton\AppData\Local\Temp\pip-install-me6l4as2\pupil-detectors
  Complete output (20 lines):
  Traceback (most recent call last):
    File "c:\users\anton\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\users\anton\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\anton\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\anton\AppData\Local\Temp\pip-build-env-y19lrlt2\overlay\Lib\site-packages\setuptools\build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\anton\AppData\Local\Temp\pip-build-env-y19lrlt2\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\anton\AppData\Local\Temp\pip-build-env-y19lrlt2\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      import numpy as np
    File "C:\Users\anton\AppData\Local\Temp\pip-build-env-y19lrlt2\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
      _win_os_check()
    File "C:\Users\anton\AppData\Local\Temp\pip-build-env-y19lrlt2\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
      raise RuntimeError(msg.format(__file__)) from None
  RuntimeError: The current Numpy installation ('C:\\Users\\anton\\AppData\\Local\\Temp\\pip-build-env-y19lrlt2\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\anton\appdata\local\programs\python\python38\python.exe' 'c:\users\anton\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\anton\AppData\Local\Temp\tmpvnrrlwvo' Check the logs for full command output.
```

**Comment by papr** [comment]
Please see this part of your error message:
> RuntimeError: The current Numpy installation ('C:\\Users\\[...]\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

Refers to https://github.com/numpy/numpy/issues/16744

Please keep your Numpy updated to get the fix as soon as it is released.
